# Generated by Django 4.1.7 on 2023-05-11 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeOrder',
            fields=[
                ('number_order', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('file_order', models.FileField(upload_to=order.models.user_directory_path, verbose_name='Накладная')),
                ('status_order', models.PositiveSmallIntegerField(choices=[(1, 'Рассмотрение'), (2, 'Начато'), (3, 'Потвержден'), (4, 'Выполнение заказа'), (5, 'Выполнен')], default=1, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('uploaded', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
